# name: Tests

# on:
#   push:
#     branches:
#       - master

# jobs:
#   tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: yarn install

#       - name: Host
#         run: yarn clean-content && yarn build-content && yarn generate

name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Host
        run: yarn clean-content && yarn build-content && yarn generate
