name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: yarn install

      - name: Host
        run: yarn clean-content && yarn build-content && yarn generate
